### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by ogezue** [cintric/CintricLocateTester#6]
I tried to integrate your library into a Swift project. When I try to get my AppDelegate I retrieve a CintricMultiDelegate:

(lldb) po UIApplication.shared.delegate!
<CintricMultiDelegate: 0x608000224240>

Have you experience with Swift projects?

**Comment by joelgreen** [comment]
@ogezue 
Did you use the SDK from the sample project? I believe it actually is not the latest. This issue should be fixed in 3.2.4 and you can download it from the docs page https://cintric.com/docs/ios

Or the direct download link is: https://cintric.com/sdk/ios

Let me know if that works.

**Comment by ogezue** [comment]
Yes - this helps. Thank you very much. 
Perhaps you should update your example project.
